# Site settings
title: Ubaydul H Sami
email: dev.sami.u@gmail.com
url: https://samihaque.github.io/
description: "Hello! I am a recent Computer Science graduate with a strong passion for Data Science and Data Analysis. This site serves as a platform to showcase my skills, projects, and professional journey. Here, you will find a detailed portfolio of my work, aimed at providing a comprehensive view of my capabilities and experiences. Whether you are a recruiter, potential employer, or simply interested in learning more about my work, I invite you to explore my projects and get to know more about my background and aspirations. Thank you for visiting!"
keywords: "data scientist, data analyst, computer science graduate, data science graduate, healthcare professional, healthcare experience, data science experience"
skills: "Data Scientist - Data Analyst - Computer Science Engineer"
meta_author: Sami Ubaydul

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: sami

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: http://www.linkedin.com/in/ubaydul-sami
  - title: github
    url: https://github.com/samihaque
  - title: codeforces
    url: https://codeforces.com/profile/Samihaque

# Postal address (add as many lines as necessary)
address:
  - line: Queens, New York

# Credits content
credits: 'This website is created using Freelancer, it's a free-to-use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
